spring.application.name=web-app
# Database
spring.datasource.url=jdbc:mysql://localhost:3307/skillmatch_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rr503052
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ORM
spring.jpa.hibernate.ddl-auto=update

# Show querries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload
file.upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Python Integration Settings (Relative paths to web-app/ directory)
ai.python.path=../ai-module/.venv/Scripts/python.exe
ai.script.path=../ai-module/main.py

